FROM alpine:3

RUN apk add --no-cache --update python3

WORKDIR /app

COPY Pipfile* ./

RUN pip3 install pipenv && pipenv install --skip-lock

COPY thesheriff thesheriff

ENV FLASK_APP=thesheriff

ENTRYPOINT [ "pipenv", "run", "flask", "run", "--host", "app"]